"""
Tests for worker/notion/client.py.

Covers initialisation validation, page creation, comment creation, and rate-limit
delay behaviour. All Notion SDK calls are mocked so no real API credentials are
required.
"""

from __future__ import annotations

import asyncio
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from notion.client import NotionClient, NotionWriteError


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_client(api_key: str = "secret_test", database_id: str = "db-123") -> NotionClient:
    """Return a NotionClient with a mocked underlying SDK client."""
    with patch("notion.client.Client"):
        client = NotionClient(api_key=api_key, database_id=database_id)
    return client


# ---------------------------------------------------------------------------
# Initialisation
# ---------------------------------------------------------------------------


def test_init_requires_api_key() -> None:
    """Empty api_key must raise ValueError immediately."""
    with pytest.raises(ValueError, match="api_key is required"):
        NotionClient(api_key="", database_id="db-123")


def test_init_requires_database_id() -> None:
    """Empty database_id must raise ValueError immediately."""
    with pytest.raises(ValueError, match="database_id is required"):
        NotionClient(api_key="secret_test", database_id="")


# ---------------------------------------------------------------------------
# create_page
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_create_page_returns_page_id() -> None:
    """
    create_page must call pages.create with the correct parent/properties and
    return the page ID from the API response.
    """
    fake_page = {"id": "page-abc-123"}

    with patch("notion.client.Client") as MockClient, patch(
        "notion.client.asyncio.to_thread", new_callable=AsyncMock
    ) as mock_to_thread, patch(
        "notion.client.asyncio.sleep", new_callable=AsyncMock
    ) as mock_sleep:
        # asyncio.to_thread returns the fake page dict
        mock_to_thread.return_value = fake_page

        client = NotionClient(api_key="secret_test", database_id="db-xyz")
        page_id = await client.create_page(
            title="Test Title",
            platform="twitter",
            content="Some content here",
            properties={
                "composite_score": 0.85,
                "score_breakdown": "signal=5,timing=4",
                "generated_at": "2026-03-20T00:00:00+00:00",
                "topic_id": 42,
                "thesis_provided": True,
                "model_used": "claude-3-5-sonnet",
                "token_cost": 0.001,
            },
        )

    assert page_id == "page-abc-123"
    # to_thread must have been called (wraps the synchronous SDK call)
    mock_to_thread.assert_called_once()
    # Rate-limit sleep must fire exactly once
    mock_sleep.assert_awaited_once_with(0.4)


@pytest.mark.asyncio
async def test_create_page_raises_notion_write_error_on_failure() -> None:
    """
    If the Notion SDK raises any exception, create_page must wrap it as
    NotionWriteError and still apply the rate-limit delay.
    """
    with patch("notion.client.Client"), patch(
        "notion.client.asyncio.to_thread", new_callable=AsyncMock
    ) as mock_to_thread, patch(
        "notion.client.asyncio.sleep", new_callable=AsyncMock
    ) as mock_sleep:
        mock_to_thread.side_effect = RuntimeError("network error")

        client = NotionClient(api_key="secret_test", database_id="db-xyz")
        with pytest.raises(NotionWriteError, match="Failed to create Notion page"):
            await client.create_page(
                title="Bad Page",
                platform="linkedin",
                content="content",
                properties={},
            )

    # Rate-limit sleep must still fire even on failure (finally block)
    mock_sleep.assert_awaited_once_with(0.4)


# ---------------------------------------------------------------------------
# add_comment
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_add_comment() -> None:
    """
    add_comment must call comments.create via to_thread and apply rate-limit delay.
    """
    with patch("notion.client.Client"), patch(
        "notion.client.asyncio.to_thread", new_callable=AsyncMock
    ) as mock_to_thread, patch(
        "notion.client.asyncio.sleep", new_callable=AsyncMock
    ) as mock_sleep:
        mock_to_thread.return_value = None

        client = NotionClient(api_key="secret_test", database_id="db-xyz")
        await client.add_comment(page_id="page-abc-123", comment_text="Generated by claude-3-5-sonnet")

    mock_to_thread.assert_called_once()
    mock_sleep.assert_awaited_once_with(0.4)


@pytest.mark.asyncio
async def test_add_comment_raises_notion_write_error_on_failure() -> None:
    """
    If the Notion SDK raises during comment creation, add_comment must wrap it
    as NotionWriteError and still apply the rate-limit delay.
    """
    with patch("notion.client.Client"), patch(
        "notion.client.asyncio.to_thread", new_callable=AsyncMock
    ) as mock_to_thread, patch(
        "notion.client.asyncio.sleep", new_callable=AsyncMock
    ) as mock_sleep:
        mock_to_thread.side_effect = RuntimeError("timeout")

        client = NotionClient(api_key="secret_test", database_id="db-xyz")
        with pytest.raises(NotionWriteError, match="Failed to add comment"):
            await client.add_comment(page_id="page-abc-123", comment_text="note")

    mock_sleep.assert_awaited_once_with(0.4)


# ---------------------------------------------------------------------------
# Rate limiting
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_rate_limiting_delay() -> None:
    """
    Both create_page and add_comment must each call asyncio.sleep(0.4) exactly
    once, even when called back-to-back.
    """
    fake_page = {"id": "page-rate-test"}

    with patch("notion.client.Client"), patch(
        "notion.client.asyncio.to_thread", new_callable=AsyncMock
    ) as mock_to_thread, patch(
        "notion.client.asyncio.sleep", new_callable=AsyncMock
    ) as mock_sleep:
        mock_to_thread.side_effect = [fake_page, None]

        client = NotionClient(api_key="secret_test", database_id="db-xyz")
        await client.create_page(
            title="Rate Test",
            platform="substack",
            content="content",
            properties={},
        )
        await client.add_comment(page_id="page-rate-test", comment_text="comment")

    assert mock_sleep.await_count == 2
    for call_args in mock_sleep.await_args_list:
        assert call_args.args == (0.4,)
